version: 2
registries: "*"
  password: ${{ secrets.CODECOV_TOKEN }}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    labels:
      - "Github Actions Update"
    schedule:
      interval: "daily"