site_name: Child Cognitive Profile Mapping (CCPM) Toolbox
repo_url: https://github.com/gagnonanthony/CCPM
repo_name: gagnonanthony/CCPM


theme:
  logo: img/CCPM.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - git-revision-date-localized
  - mkapi:
      exclude:
        - CCPM.tests

nav:
  - Home: 'index.md'
  - 'Scripts':
    - $api/Scripts.*
  - 'API Reference':
    - $api/CCPM.**
  - 'About': 
    - 'License': 'license.md'

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gagnonanthony/CCPM.git
  version:
    default: latest

markdown_extensions:
  - mkdocs-typer
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/gagnonanthony"  target="_blank" rel="noopener">Anthony Gagnon</a>