[tool.poetry]
name = "ccpm"
version = "0.1.0"
description = "Children Cognitive Profiles Mapping Toolbox (CCPM)"
authors = ["Anthony Gagnon <anthony.gagnon7@usherbrooke.ca>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/gagnonanthony/CCPM.git"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.2"
pandas = "^2.1.3"
scikit-learn = "^1.3.2"
scikit-fuzzy = "^0.4.2"
scipy = "1.11.4"
semopy = "^2.3.10"
graphviz = "^0.20.1"
p-tqdm = "^1.4.0"
pytest = "^7.4.3"
seaborn = "0.12.2"
gdown = "^4.7.1"
kneed = "^0.8.5"
detect-delimiter = "^0.1.1"
Pillow = "^10.2.0"
factor-analyzer = "^0.5.0"
matplotlib = "^3.8.2"
networkx = "^3.2.1"
typer = {extras = ["all"], version = "^0.9.0"}
coloredlogs = "^15.0.1"
tableone = "^0.8.0"
statannotations = {git = "https://github.com/gagnonanthony/statannotations.git"}
adjusttext = "^1.0.4"
strenum = "^0.4.15"

[tool.poetry.scripts]
CCPM_compute_graph_network = 'Scripts.CCPM_compute_graph_network:app'
CCPM_compare_clustering = 'Scripts.CCPM_compare_clustering:app' 
CCPM_compare_graph_network = 'Scripts.CCPM_compare_graph_network:app'
CCPM_compute_weighted_path = 'Scripts.CCPM_compute_weighted_path:app'
CCPM_creating_medical_statistics = 'Scripts.CCPM_creating_medical_statistics:app'
CCPM_factor_analysis = 'Scripts.CCPM_factor_analysis:app'
CCPM_filtering_dataset = 'Scripts.CCPM_filtering_dataset:app'
CCPM_fuzzy_clustering = 'Scripts.CCPM_fuzzy_clustering:app'
CCPM_graph_metrics = 'Scripts.CCPM_graph_metrics:app'
CCPM_predict_fuzzy_membership = 'Scripts.CCPM_predict_fuzzy_membership:app'
CCPM_set_nodes_attributes = 'Scripts.CCPM_set_nodes_attributes:app'
CCPM_plsr = 'Scripts.CCPM_plsr:app'

[tool.poetry.group.dev.dependencies]
coverage = "^7.3.2"
pytest = "^7.4.3"
flake8 = "^6.1.0"
coverage-badge = "^1.1.0"
ipykernel = "^6.27.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"