[tool.poetry]
name = "CCPM"
version = "0.0.0"
description = "Children Cognitive Profiles Mapping Toolbox (CCPM)"
authors = ["Anthony Gagnon <anthony.gagnon7@usherbrooke.ca>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/gagnonanthony/CCPM.git"

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.2"
pandas = "^2.1.3"
scikit-learn = "^1.3.2"
scikit-fuzzy = "^0.4.2"
scipy = "1.11.4"
semopy = "^2.3.10"
graphviz = "^0.20.1"
p-tqdm = "^1.4.0"
seaborn = "0.12.2"
gdown = "5.1.0"
kneed = "^0.8.5"
detect-delimiter = "^0.1.1"
Pillow = "^10.2.0"
factor-analyzer = "^0.5.0"
matplotlib = "^3.8.2"
networkx = "^3.2.1"
coloredlogs = "^15.0.1"
statannotations = {git = "https://github.com/gagnonanthony/statannotations.git"}
adjusttext = "^1.0.4"
strenum = "^0.4.15"
cyclopts = "^2.2.0"
openpyxl = "^3.1.2"

[tool.poetry.scripts]
ComputeGraphNetwork = "Scripts.ComputeGraphNetwork:app"
CompareClustering = "Scripts.CompareClustering:app" 
CompareGraphs = "Scripts.CompareGraphs:app"
AverageWeightedPath = "Scripts.AverageWeightedPath:app"
FactorAnalysis = "Scripts.FactorAnalysis:app"
FuzzyClustering = "Scripts.FuzzyClustering:app"
GraphMetrics = "Scripts.GraphMetrics:app"
PredictFuzzyMembership = "Scripts.PredictFuzzyMembership:app"
AddNodesAttributes = "Scripts.AddNodesAttributes:app"
Plsr = "Scripts.Plsr:app"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
flake8 = "^6.1.0"
ipykernel = "^6.27.1"
pytest-console-scripts = "^1.4.1"

[tool.poetry.group.debug]
optional = true

[tool.poetry.group.debug.dependencies]
ipdb = ">=0.13.9"
line_profiler = ">=3.5.1"

[tool.pytest.ini_options]
pythonpath = [
    "."
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"