name: Continuous Integration

on:
  pull_request:
    branches:
      - main
    types: [opened,reopened,synchronize]
    paths:
      - 'CCPM/**/*.py'
      - 'Scripts/*.py'
      - 'setup.py'
      - '!.github/**'
      - '.github/workflows/*.yml'
  push:
    branches:
      - main

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name : Install flake8
        run: |
          pip install flake8
      - name: Lint with flake8
        run: |
          flake8 . --count --ignore=W605 --show-source --statistics

  Building:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Install Graphviz
        uses: tlylt/install-graphviz@v1.0.0
      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
            version: 1.7.1
            virtualenvs-create: true
            installer-parallel: true
      - name: Install CCPM & dependencies
        run: |
          poetry install --with=dev

  Testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Install Graphviz
        uses: tlylt/install-graphviz@v1.0.0
      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
            version: 1.7.1
            virtualenvs-create: true
            installer-parallel: true
      - name: Install CCPM & dependencies
        run: |
          poetry install --with=dev
      - name: Pytest
        run: |
          poetry run pytest --cov=[CCPM,Scripts] --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}