name: Build & Development

on:
  pull_request:
    branches:
      - main
    types: [opened,reopened,synchronize]
    paths:
      - 'CCPM/**/*.py'
      - 'Scripts/*.py'
      - 'setup.py'
      - '!.github/**'
      - '.github/workflows/*.yml'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Setting up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install CCPM and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
      - name: Test with pytest
        run: |
          pytest