name: Build & Development

on:
  pull_request:
    branches:
      - main
    types: [opened,reopened,synchronize]
    paths:
      - 'CCPM/**/*.py'
      - 'Scripts/*.py'
      - 'setup.py'
      - '!.github/**'
      - '.github/workflows/*.yml'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - name: Setting up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
            version: 1.7.1
            virtualenvs-create: true
            installer-parallel: true
      - name: Install CCPM & dependencies
        run: |
          poetry install
      - name: Test with pytest
        run: |
          poetry run pytest --verbose