name: Build & Development

on:
  pull_request:
    branches:
      - main
    types: [opened,reopened,synchronize]
    paths:
      - 'CCPM/**/*.py'
      - 'Scripts/*.py'
      - 'setup.py'
      - '!.github/**'
      - '.github/workflows/*.yml'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Install Graphviz
        uses: tlylt/install-graphviz@v1.0.0
      - name: Setting up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
            version: 1.7.1
            virtualenvs-create: true
            installer-parallel: true
      - name: Install CCPM & dependencies
        run: |
          poetry install --with=dev
      - name: Lint with flake8
        run: |
          poetry run flake8 . --count --ignore=W605 --show-source --statistics
      - name: Pytest
        run: |
          poetry run coverage run -m pytest --verbose && \
          poetry run coverage report -m && \
          poetry run coverage xml && \
          poetry run coverage-badge -f -o coverage.svg

  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}